fix for amplify.yml build script

diff --git a/amplify.yml b/amplify.yml
--- a/amplify.yml
+++ b/amplify.yml
@@ -234,32 +234,37 @@ applications:
 
 #========================================
   - appRoot: apps/pixelated
+    env:
+      variables:
+        AMPLIFY_MONOREPO_APP_ROOT: "apps/pixelated"
     frontend:
       phases:
         preBuild:
           commands:
             - |
+              echo "Env Var AMPLIFY_MONOREPO_APP_ROOT = $AMPLIFY_MONOREPO_APP_ROOT"
               APP_DIR=$(basename $(pwd))
-              echo "Installing dependencies for monorepo..."
+              echo "Installing dependencies for monorepo: $APP_DIR ..."
               cd ../../ && pwd
               npm install --force
               echo "Dependencies installed"
         build:
           commands:
             - |
-              APP_DIR=apps/pixelated
-              echo "Building shared components..."
+              APP_DIR=$(basename $(pwd))
+              PARENT_DIR=$(basename $(dirname $(pwd)))
+              echo "Building shared components: $PARENT_DIR/$APP_DIR ..."
               npm run build -w packages/pixelated-components
               echo "Building Next.js app: $APP_DIR ..."
-              npm run build -w $APP_DIR
-              npm run generate-site-images -w $APP_DIR
+              npm run build -w $PARENT_DIR/$APP_DIR
+              npm run generate-site-images -w $PARENT_DIR/$APP_DIR
         postBuild:
           commands:
-            - echo "Calling Config Vault postbuild"
-            - pwd
-            - ls -la src/app/config || true
-            - ls -la .next/server || true
-            - npm run config:vault -- postbuild || (echo "Config postbuild decrypt failed" && exit 1)
+            - echo "Calling Config Vault postbuild: "
+            - |
+              ls -la src/app/config || true
+              ls -la .next/server || true
+              npm run config:vault -- postbuild || (echo "Config postbuild decrypt failed" && exit 1)
       artifacts:
         baseDirectory: .next
         files:
