amplify.yml and erlease.sh fixes

diff --git a/amplify.yml b/amplify.yml
--- a/amplify.yml
+++ b/amplify.yml
@@ -11,40 +11,29 @@ applications:
           commands:
             - |
               APP_DIR=$(basename $(pwd))
+              git fetch origin main --depth=1 || true
               CHANGED=$(git diff --name-only origin/main...HEAD | grep -E "^apps/$APP_DIR/" | wc -l)
               if [ "$CHANGED" -eq 0 ]; then
                 echo "No changes detected for $APP_DIR. Build will be skipped."
-                touch SKIP_BUILD_TOKEN
-              else
-                echo "Changes detected for $APP_DIR. Proceeding with build."
-                echo "Installing dependencies for monorepo..."
-                node -v && npm -v
-                pwd
-                npm install --force
-                echo "Dependencies installed"
+                exit 1
               fi
+              echo "Changes detected for $APP_DIR. Proceeding with build."
+              echo "Installing dependencies for monorepo..."
+              node -v && npm -v
+              pwd
+              npm install --force
+              echo "Dependencies installed"
         build:
           commands:
-            - |
-              if [ -f "SKIP_BUILD_TOKEN" ]; then
-                echo "Skipping build phase..."
-                mkdir -p .next
-              else
-                echo "Building shared components..."
-                npm run build -w packages/pixelated-components
-                echo "Building Next.js app..."
-                npm run build -w apps/brianwhaley
-                npm run generate-site-images -w apps/brianwhaley
-              fi
+            - echo "Building shared components..."
+            - npm run build -w packages/pixelated-components
+            - echo "Building Next.js app..."
+            - npm run build -w apps/brianwhaley
+            - npm run generate-site-images -w apps/brianwhaley
         postBuild:
           commands:
-            - |
-              if [ -f "SKIP_BUILD_TOKEN" ]; then
-                echo "Skipping postBuild."
-              else
-                echo "Calling Config Vault postbuild"
-                npm run config:vault -- postbuild|| (echo "Config postbuild decrypt failed" && exit 1)
-              fi
+            - echo "Calling Config Vault postbuild"
+            - npm run config:vault -- postbuild || (echo "Config postbuild decrypt failed" && exit 1)
       artifacts:
         baseDirectory: .next
         files:
